version: '3.8'

services:
  request-service:
    build:
      dockerfile: ./requests.dockerfile
      target: dev
      context: ./
      
    image: ninjeneer/vuln-scanner-request-service
    ports:
      - 3000:3000
    volumes:
     - .:/app
    networks:
      - vulnscanner

  report-service:
    build:
      dockerfile: ./reports.dockerfile
      target: dev
      context: ./
    
    image: ninjeneer/vuln-scanner-report-service
    ports:
      - 3001:3000
    volumes:
      - .:/app
    networks:
      - vulnscanner

  jobs-service:
    build:
      dockerfile: ./jobs.dockerfile
      target: dev
      context: ./
    
    image: ninjeneer/vuln-scanner-jobs-service
    volumes:
      - .:/app
    networks:
      - vulnscanner

  billing-service:
    build:
      dockerfile: ./billing.dockerfile
      target: dev
      context: ./
    
    image: ninjeneer/vuln-scanner-billing-service
    ports:
      - 3002:3000
    volumes:
      - .:/app
    networks:
      - vulnscanner

  stats-service:
    build:
      dockerfile: ./stats.dockerfile
      target: dev
      context: ./
    
    image: ninjeneer/vuln-scanner-stats-service
    ports:
      - 3003:3000
    volumes:
      - .:/app
    networks:
      - vulnscanner

  global-service:
    build:
      dockerfile: ./global.dockerfile
      target: dev
      context: ./
    
    image: ninjeneer/vuln-scanner-global-service
    volumes:
      - .:/app
    networks:
      - vulnscanner

networks:
  vulnscanner:
    name: vulnscanner
    external: true