version: '3.8'

services:
  request-service:
    build:
      dockerfile: ./Dockerfile
      target: dev
      context: ./
      
    image: vuln-request-service
    ports:
      - 3000
    volumes:
     - .:/app

  report-service:
    build:
      dockerfile: ../VulnScannerReportService/Dockerfile
      target: dev
      context: ../VulnScannerReportService
    
    image: vuln-report-service
    ports:
      - 3000
    volumes:
      - ../VulnScannerReportService:/app