version: '3.8'

services:
  request-service:
    build:
      dockerfile: ./Dockerfile
      target: dev
      context: ./
      
    image: vuln-request-service
    ports:
      - 3001:3000
    volumes:
     - .:/app