version: '3.8'

services:
  request-service:
    build:
      dockerfile: ./requests.dockerfile
      target: dev
      context: ./
      
    image: ninjeneer/vuln-request-service
    ports:
      - 3000:3000
    volumes:
     - .:/app
    networks:
      - vulnscanner

  report-service:
    build:
      dockerfile: ./reports.dockerfile
      target: dev
      context: ./
    
    image: ninjeneer/vuln-report-service
    ports:
      - 3001:3000
    volumes:
      - .:/app
    networks:
      - vulnscanner

networks:
  vulnscanner:
    name: vulnscanner
    external: true